title_primary: "静言思辨" # the bigger text
title_secondary: "Que sera sera" # the smaller text
keywords:

twitter: Vancirprince
rss: atom.xml
weibo: 5226074301
instagram: #username
github: vancir

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] on livere.com
disqus: # [short_name] on disqus.com
dove: # For fun ONLY. Set to true to 'disable' comments on your site.

# Set true to show the page indicator.
showPageCount: true

# Set true to show category or tags behind post titles
showCategories: false
showTags: false

# Color scheme
themeStyle: light # light/dark
